-- Fix venues columns
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS cover TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS avatar TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS rating NUMERIC(2,1) DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS reviews INT DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS capacity INT DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS is_open BOOLEAN DEFAULT FALSE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS open_hours TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS description TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT FALSE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS amenities TEXT[] DEFAULT '{}'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS price_range INT DEFAULT 2; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS address TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS name TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'club'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.venues ADD COLUMN IF NOT EXISTS city TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Fix events columns
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS venue_id TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS venue_name TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS title TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS description TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS time TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS end_time TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS cover TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS category TEXT[] DEFAULT '{}'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS price NUMERIC(10,2) DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS capacity INT DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS attending INT DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS is_online BOOLEAN DEFAULT FALSE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS is_premium BOOLEAN DEFAULT FALSE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS artists TEXT[] DEFAULT '{}'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS lng DOUBLE PRECISION DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS date DATE DEFAULT CURRENT_DATE; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.events ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'EUR'; EXCEPTION WHEN OTHERS THEN NULL; END $$;

-- Fix services columns
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS artist_name TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS artist_avatar TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS title TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS description TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS category TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS price NUMERIC(10,2) DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS delivery_days INT DEFAULT 1; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS rating NUMERIC(2,1) DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS reviews INT DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS orders INT DEFAULT 0; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS cover TEXT DEFAULT ''; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS includes TEXT[] DEFAULT '{}'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.services ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'EUR'; EXCEPTION WHEN OTHERS THEN NULL; END $$;
